#!/bin/sh

source ./Configuration

rm -rf haproxy.cfg

# generate the appropriate haproxy.cfg
if [ "`uname -n | cut -d'.' -f1`" == "bhmgiweb01lt" ] 
then
	ln -s haproxy.cfg.test haproxy.cfg
elif [ "`uname -n | cut -d'.' -f1`" == "bhmgipubweb01lp" ]
then
	ln -s haproxy.cfg.pub1 haproxy.cfg
elif [ "`uname -n | cut -d'.' -f1`" == "bhmgipubweb02lp" ] 
then
	ln -s haproxy.cfg.pub2 haproxy.cfg
#else 
#	do this manually and chosse the proper haproxy.cfg

fi

# start the proxy
./startProxy

